AdminDashBoard/Models/ErrorViewModel.cs
namespace AdminDashBoard.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdminDashBoard/Models/RoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminDashBoard.Models
{
    public class RoleViewModel
    {
        [Required(ErrorMessage = "Role Is Required")]
        [StringLength(256, ErrorMessage = "Role Length Should Be less Than 256 char ")]
        public string Name { get; set; } = default!;
    }
}

AdminDashBoard/Models/UpdateRoleViewModel.cs
namespace AdminDashBoard.Models
{
    public class UpdateRoleViewModel
    {
        public string Id { get; set; } = default!;
        public string Name { get; set; } = default!;
        public bool IsSelected {  get; set; }
    }
}

AdminDashBoard/Models/UserRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminDashBoard.Models
{
    public class UserRoleViewModel
    {
       

        public string UserName {  get; set; } = default!;

        public List<UpdateRoleViewModel> Roles { get; set; } = [];

    }



}

AdminDashBoard/Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AdminDashBoard.Models
{
    public class UserViewModel
    {
        public string Id { get; set; } = default!;

        [Display(Name ="Display Name")]
        public string DisplayName { get; set; }=default!;

        public string Email { get; set; } = default!;
        public string UserName {  get; set; } = default!;
        public IEnumerable<string> Roles { get; set; }
    }
}

AdminDashBoard/Controllers/HomeController.cs
using AdminDashBoard.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdminDashBoard.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdminDashBoard/Controllers/RoleController.cs
using AdminDashBoard.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace AdminDashBoard.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()

        {

           var Roles=await _roleManager.Roles.ToListAsync();
            return View(Roles);
        }


        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel roleView)
        {
            if(!ModelState.IsValid)
               return RedirectToAction(nameof(Index));
            else
            {
                var RoleExists = await _roleManager.RoleExistsAsync(roleView.Name);

                if (!RoleExists) {

                    var Role = await _roleManager.CreateAsync(new IdentityRole()
                    {
                        Name = roleView.Name,
                    });

                 return   RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Name", "Role Already Exists");
                    return View(nameof(Index),await _roleManager.Roles.ToListAsync() );
                }

           
              
            
              
                
                    
                
            }
        }

     
        public async Task<IActionResult> Delete(string Id)
        {
            var role=await _roleManager.FindByIdAsync(Id);

            if(role != null)
                await _roleManager.DeleteAsync(role);


                return RedirectToAction(nameof(Index));
                
        }


        #region Edit

        [HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {
            
            var role = await _roleManager.FindByIdAsync(Id);
            if(role != null)
           {
                var RoleView = new UpdateRoleViewModel()
                {
                    Name = role.Name,
                };
                
                return View(RoleView); }
            else
            {
                ModelState.AddModelError("Id", "Not Role Fount This Id");
                return RedirectToAction(nameof(Index));
            }
        }


        [HttpPost]

        public async Task<IActionResult> Edit([FromRoute] string Id, UpdateRoleViewModel updateRoleView)
        {

            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(Id);

                role.Name=updateRoleView.Name;

                var RoleExists = await _roleManager.RoleExistsAsync(updateRoleView.Name);

                if (!RoleExists)
                {

                    await _roleManager.UpdateAsync(role);
                    return RedirectToAction(nameof(Index));


                }

                ModelState.AddModelError("Name", "Role Is Already Exits");



            }

            return View(updateRoleView);
        }
            #endregion

        }
}

AdminDashBoard/Controllers/UserController.cs
using AdminDashBoard.Models;
using Domain.Models.IdentityModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace AdminDashBoard.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<ApplicationUser> userManager,RoleManager<IdentityRole> roleManager )
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var Users = await _userManager.Users.Select(U => new UserViewModel()
            {
                Id = U.Id,
                DisplayName = U.DisplayName,
                Email = U.Email!,
                UserName = U.UserName!,

                Roles = _userManager.GetRolesAsync(U).Result
            }).ToListAsync();


            return View(Users);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id) { 
        var user=await _userManager.FindByIdAsync(id);

            var role=await _roleManager.Roles.ToListAsync();


            var UserRole = new UserRoleViewModel()
            {
              
                UserName = user.UserName
                  ,
                Roles = role.Select(r => new UpdateRoleViewModel()
                {
                    Id = r.Id,
                    Name = r.Name,

                    IsSelected = _userManager.IsInRoleAsync(user,r.Name).Result

                }).ToList()
            };  

            return View(UserRole);
        
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] string id, UserRoleViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);

            var roles = await _userManager.GetRolesAsync(user);

            foreach (var role in model.Roles)
            {

                if (roles.Any(r => r == role.Name) && !role.IsSelected)
                    await _userManager.RemoveFromRoleAsync(user, role.Name);
                else if (!roles.Any(r => r == role.Name) && role.IsSelected)
                    await _userManager.AddToRoleAsync(user, role.Name);


            }

            return RedirectToAction(nameof(Index));
        }
    }
}

AdminDashBoard/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AdminDashBoard/Views/Role/Edit.cshtml
@model UpdateRoleViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1 class="mt-2 text-center">Edit Role</h1>

<br/>

<form class="mt-4" asp-action="Edit" method="post">

    <div class="form-group mt-4">
        
        <label  asp-for="@Model.Name"></label>
        <input asp-for="@Model.Name" class="form-control"/>
        <span class="text-danger" asp-validation-for="@Model.Name"></span>
        <div class="input-group mt-2 justify-content-center ">

            <button type="submit" class="btn btn-success rounded-2">Save</button>

            <a asp-action="Index" class="btn btn-outline-dark rounded-2"> Go Back</a>

        </div>
    
    </div>

</form>

AdminDashBoard/Views/Role/Index.cshtml
 @model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "Index";
}

<h1 class="mt-2 text-center ">All Roles</h1>

<partial name="PartialView/CreateEditRolePartialView.cshtml" model="new RoleViewModel()" />

@if(Model.Count() > 0)
{
    <table class="table table-hover table-striped">

        <thead>
            <tr>
                <th scope="col">@Html.DisplayNameFor(R=>R.Id)</th>
                <th scope="col">@Html.DisplayNameFor(R => R.Name)</th>
                <td>Action</td>

            </tr>
        </thead>
        <tbody>

            @foreach(var role in Model)
            {<tr>

                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td><a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@role.Id">Edit </a>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@role.Id">Delete </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}
else
{
    <p class="mt-3 p-2 alert alert-warning">There Are No Role yet </p>
}

AdminDashBoard/Views/Role/PartialView/CreateEditRolePartialView.cshtml
@model RoleViewModel

<form method="post" asp-controller="Role" asp-action="Create">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="input-group mb-2">
        <input class="form-control rounded-2 mt-2" asp-for="@Model.Name" placeholder="Enter the Role Name" />
        <div class="input-group-append mt-2">
            <button class="btn btn-success">Create</button>
        </div>
    </div>

    <span asp-validation-for="@Model.Name" class="text-danger"></span>

</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
}

AdminDashBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminDashBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminDashBoard.styles.css" asp-append-version="true" />

    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Start Bootstrap</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </form>
        <!-- Navbar-->
    
    </nav>


    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Security</div>
                    
                     
                        
                      
                        <a class="nav-link" asp-controller="Role" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Roles
                        </a>
                        <a class="nav-link" asp-controller="User" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                           Uses
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


   

 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/scripts.js"></script>
    
  
   

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdminDashBoard/Views/User/Edit.cshtml
@model UserRoleViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit @Model.UserName</h1>


<div class="container">

    <form asp-action="Edit" method="post" >

        <div>
            <label asp-for="UserName" class="col-form-label"></label>
            <input  asp-for="UserName" class="form-control" readonly/>
        </div>

        <h3>Manage @Model.UserName Roles</h3>
        <hr/>

        @for(int i = 0; i < Model.Roles.Count; i++)
        {
          <div>
              <input asp-for="@Model.Roles[i].Id" hidden/>
              <input asp-for="@Model.Roles[i].Name" hidden/>
              <input asp-for="@Model.Roles[i].IsSelected" class="col-form-label"/>
              <label asp-for="@Model.Roles[i].Name" class="col-form-label">@Model.Roles[i].Name</label>
              <span asp-validation-for="@Model.Roles[i].IsSelected"></span>
          </div>  
        }
        <br/>

        <div class="input-group mt-2 justify-content-center">

            <button type="submit" class="btn btn-success m-2 rounded-2">Save</button>
            <a asp-action="Index" class="btn  btn-outline-dark m-2 rounded-2">Back To List </a>


        </div>
    </form>
</div>

AdminDashBoard/Views/User/Index.cshtml
@model IEnumerable<UserViewModel>
@{
    ViewData["Title"] = "Index";
}

<h1 class="mt-2 text-center ">All users</h1>



@if (Model.Count() > 0)
{
    <table class="table table-hover table-striped">

        <thead>
            <tr>
                <th scope="col">@Html.DisplayNameFor(u => u.Id)</th>
                <th scope="col">@Html.DisplayNameFor(u => u.DisplayName)</th>
                <th scope="col">@Html.DisplayNameFor(u => u.Email)</th>
                <th scope="col">@Html.DisplayNameFor(u => u.UserName)</th>
                <th scope="col">@Html.DisplayNameFor(u => u.Roles)</th>
                <td>Action</td>

            </tr>
        </thead>
        <tbody>

            @foreach (var user in Model)
            {
                <tr>

                    <td>@user.Id</td>
                    <td>@user.DisplayName</td>
                    <td>@user.Email</td>
                    <td>@user.UserName</td>
                    <td>@string.Join(",",user.Roles.ToList())</td>
                    <td>
                        <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@user.Id">Edit </a>
                     
                    </td>
                </tr>
            }
        </tbody>
    </table>

}
else
{
    <p class="mt-3 p-2 alert alert-warning">There Are No user yet </p>
}